export const DOCTORS = [
  {
    id: 0,
    name: "امیرعلی نجات",
    image: require("../images/DocImage1.jpg"),
    gender: "3",
    profession: "پزشک عمومی",
    pro: "2",
  },
  {
    id: 1,
    name: "سیروس افشار",
    image: require("../images/DocImage2.jpg"),
    gender: "3",
    profession: "متخصص گوارش",
    pro: "3",
  },
  {
    id: 2,
    name: "مهناز فروتن",
    image: require("../images/DocImage3.jpg"),
    gender: "2",
    profession: "متخصص داخلی",
    pro: "4",
  },
  {
    id: 3,
    name: "امیرعلی نجات",
    image: require("../images/DocImage4.jpg"),
    gender: "3",
    profession: "پزشک عمومی",
    pro: "2",
  },
  {
    id: 4,
    name: "سیروس افشار",
    image: require("../images/DocImage5.jpg"),
    gender: "3",
    profession: "متخصص گوارش",
    pro: "3",
  },
  {
    id: 5,
    name: "مهناز فروتن",
    image: require("../images/DocImage6.jpg"),
    gender: "2",
    profession: "متخصص داخلی",
    pro: "4",
  },
  {
    id: 6,
    name: "امیرعلی نجات",
    image: require("../images/DocImage1.jpg"),
    gender: "3",
    profession: "پزشک عمومی",
    pro: "2",
  },
  {
    id: 7,
    name: "سیروس افشار",
    image: require("../images/DocImage2.jpg"),
    gender: "3",
    profession: "متخصص گوارش",
    pro: "3",
  },
  {
    id: 8,
    name: "مهناز فروتن",
    image: require("../images/DocImage3.jpg"),
    gender: "2",
    profession: "متخصص داخلی",
    pro: "4",
  },
  {
    id: 9,
    name: "امیرعلی نجات",
    image: require("../images/DocImage4.jpg"),
    gender: "3",
    profession: "پزشک عمومی",
    pro: "2",
  },
  {
    id: 10,
    name: "سیروس افشار",
    image: require("../images/DocImage5.jpg"),
    gender: "3",
    profession: "متخصص گوارش",
    pro: "3",
  },
  {
    id: 11,
    name: "مهناز فروتن",
    image: require("../images/DocImage6.jpg"),
    gender: "2",
    profession: "متخصص داخلی",
    pro: "4",
  },
];
